<a href="https://colab.research.google.com/github/looooore/Pytorch_Colab/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSORS

*   Um tensor do PyTorch é uma matriz multidimensional que contém elementos de um único tipo de dado.

*   É semelhante aos arrays do NumPy, mas com recursos adicionais que permitem seu uso eficiente em GPUs (além das CPUs).
*   O tipo de dado padrão é **float32**.
*   É mais adequado para aprendizado profundo (deep learning) do que um array do NumPy, pois integra suporte a autograd, GPU e operações otimizadas.

In [ ]:
import torch
import numpy as np

# LISTS

In [ ]:
my_list = [1,2,3,4,5], [6,7,8,9,10]
my_list

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])

# NUMPY ARRAYS

In [ ]:
np1 = np.random.rand(2,2)
np1

array([[0.39111586, 0.88336183],
       [0.69716641, 0.09627115]])

In [ ]:
np1.dtype

dtype('float64')

# TENSORS

In [ ]:
tensor_2d = torch.randn(4,4)
tensor_2d

tensor([[ 1.4546,  0.5142, -0.6868, -0.0998],
        [-0.1866, -0.4688,  1.3293, -0.0518],
        [ 0.1871, -0.5648, -0.2754, -0.0349],
        [-0.1571,  0.6602, -0.5416,  0.3492]])

In [ ]:
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(4,4,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3911, 0.8834],
        [0.6972, 0.0963]], dtype=torch.float64)